[healthCheck_log]
SHOULD_LINEMERGE= false
LINE_BREAKER= ([\r\n]+)
TIME_PREFIX = ^
TIME_FORMAT = %b %d %H:%M:%S %z
MAX_TIMESTAMP_LOOKAHEAD = 21
TRUNCATE = 1024
EVENT_BREAKER_ENABLE = true
EVENT_BREAKER = ([\r\n]+)
