[flog_access_log]
coldPath = $SPLUNK_DB/flog_access_log/colddb
homePath = $SPLUNK_DB/flog_access_log/db
maxTotalDataSizeMB = 100
thawedPath = $SPLUNK_DB/flog_access_log/thaweddb

[flog_client_errors_log]
coldPath = $SPLUNK_DB/flog_client_errors_log/colddb
homePath = $SPLUNK_DB/flog_client_errors_log/db
maxTotalDataSizeMB = 100
thawedPath = $SPLUNK_DB/flog_client_errors_log/thaweddb

[pythonloggen_log]
coldPath = $SPLUNK_DB/pythonloggen_log/colddb
homePath = $SPLUNK_DB/pythonloggen_log/db
maxTotalDataSizeMB = 100
thawedPath = $SPLUNK_DB/pythonloggen_log/thaweddb

[lab_monitoring]
coldPath = $SPLUNK_DB/lab_monitoring/colddb
homePath = $SPLUNK_DB/lab_monitoring/db
maxTotalDataSizeMB = 100
thawedPath = $SPLUNK_DB/lab_monitoring/thaweddb
