[flog_access]
RULESET-ruleset_flog_access = _rule:ruleset_flog_access:mask::m69k5wcs _rule:ruleset_flog_access:filter:regex:fd7s8rej
RULESET_DESC-ruleset_flog_access = Mask host IP address & Drop redirect logs
