[_rule:ruleset_flog_access:filter:regex:fd7s8rej]
INGEST_EVAL = queue=if(match(_raw, "\\\"status\\\":\\s*3\\d\\d\\b"), "nullQueue", queue)
STOP_PROCESSING_IF = queue == "nullQueue"

[_rule:ruleset_flog_access:mask::m69k5wcs]
INGEST_EVAL = _raw:=replace(_raw, "(\\\"host\\\"\\:\\\")(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})(\\\"\\,)", "\\1\\2.XXX.XXX.XXX\\6")
