[flog_access]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TIME_PREFIX = \"datetime\":\"
MAX_TIMESTAMP_LOOKAHEAD = 32
TIME_FORMAT = %d/%b/%Y:%H:%M:%S %z
TRUNCATE = 4096
EVENT_BREAKER_ENABLE = true
EVENT_BREAKER = ([\r\n]+)
SEDCMD-mask_userid = s/"user-identifier":"([^"-][^"]{0,1})[^"]*"/"user-identifier":"\1***"/g
TRANSFORMS-filter = flog_ignoresuccess
TRANSFORMS-route = flog_client_errors_to_index
