[flog_ignoresuccess]
REGEX = "status":\s*2\d\d\b
DEST_KEY = queue
FORMAT = nullQueue

[flog_client_errors_to_index]
REGEX = "status":\s*4\d\d\b
DEST_KEY = _MetaData:Index
FORMAT = flog_client_errors_log
