[serverClass:all_host]
machineTypesFilter = linux-x86_64
whitelist.0 = idx*
whitelist.1 = sh*
whitelist.2 = hf*
blacklist.0 = ds*
blacklist.1 = uf*

[serverClass:all_host:app:all_license_peer]
restartSplunkd = true
stateOnClient = enabled

[serverClass:indexer]
machineTypesFilter = linux-x86_64
whitelist.0 = idx*

[serverClass:indexer:app:all_indexes]
restartSplunkd = true
stateOnClient = enabled

[serverClass:indexer:app:idx_base]
restartSplunkd = true
stateOnClient = enabled

[serverClass:indexer:app:all_receiving]
restartSplunkd = true
stateOnClient = enabled

[serverClass:forwarder]
machineTypesFilter = linux-x86_64
whitelist.0 = uf*

[serverClass:forwarder:app:flog_inputs]
restartSplunkd = true
stateOnClient = enabled

[serverClass:forwarder:app:uf_outputs_to_hf]
restartSplunkd = true
stateOnClient = enabled

[serverClass:heavy_forwarder]
machineTypesFilter = linux-x86_64
whitelist.0 = hf*

[serverClass:heavy_forwarder:app:all_receiving]
restartSplunkd = true
stateOnClient = enabled

[serverClass:heavy_forwarder:app:all_outputs_to_idx]
restartSplunkd = true
stateOnClient = enabled

[serverClass:heavy_forwarder:app:hf_outputs]
restartSplunkd = true
stateOnClient = enabled

[serverClass:heavy_forwarder:app:flog_props_index]
restartSplunkd = true
stateOnClient = enabled

[serverClass:heavy_forwarder:app:splunk_ingest_actions]
restartSplunkd = true
stateOnClient = enabled

[serverClass:heavy_forwarder:app:all_web_base]
restartSplunkd = true
stateOnClient = enabled

[serverClass:heavy_forwarder:app:pythonLogGen_inputs]
restartSplunkd = true
stateOnClient = enabled

[serverClass:heavy_forwarder:app:pythonLogGen_props_index]
restartSplunkd = true
stateOnClient = enabled

[serverClass:heavy_forwarder:app:healthCheck_inputs]
restartSplunkd = true
stateOnClient = enabled

[serverClass:heavy_forwarder:app:healthCheck_props_index]
restartSplunkd = true
stateOnClient = enabled

[serverClass:heavy_forwarder:app:hf_hec]
restartSplunkd = true
stateOnClient = enabled

[serverClass:heavy_forwarder:app:caddy_inputs]
restartSplunkd = true
stateOnClient = enabled

[serverClass:heavy_forwarder:app:all_deployment_key]
restartSplunkd = true
stateOnClient = enabled

[serverClass:search_heads]
whitelist.0 = sh*

[serverClass:search_heads:app:all_web_base]
restartSplunkd = true
stateOnClient = enabled

[serverClass:search_heads:app:flog_props_search]
restartSplunkd = true
stateOnClient = enabled

[serverClass:search_heads:app:caddy_props_search]
restartSplunkd = true
stateOnClient = enabled

[serverClass:search_heads:app:all_outputs_to_idx]
restartSplunkd = true
stateOnClient = enabled

# Ingest actions should only go on the heavy forwarders
# Overrides the auto generated one
[serverClass:100_IngestAction_AutoGenerated]
whitelist.0 = hf*
