[serverClass:all_host]
machineTypesFilter = linux-x86_64
whitelist.0 = idx*
whitelist.1 = sh*
whitelist.2 = uf*
blacklist.0 = ds1

[serverClass:all_host:app:license_peer_config]
restartSplunkd = true
stateOnClient = enabled

[serverClass:indexer]
machineTypesFilter = linux-x86_64
whitelist.0 = idx*

[serverClass:indexer:app:flog_props_index]
restartSplunkd = false
stateOnClient = enabled

[serverClass:indexer:app:1_all_indexes]
restartSplunkd = true
stateOnClient = enabled

[serverClass:indexer:app:1_indexer_base]
restartSplunkd = true
stateOnClient=enabled

[serverClass:forwarder]
machineTypesFilter = linux-x86_64
whitelist.0 = uf*

[serverClass:forwarder:app:flog_forwarder_inputs]
restartSplunkd = false
stateOnClient = enabled

[serverClass:forwarder:app:1_all_forwarder_outputs]
restartSplunkd = true
stateOnClient = enabled

[serverClass:search_heads]
whitelist.0 = sh*

[serverClass:search_heads:app:all_web_base]
restartSplunkd = true
stateOnClient = enabled

[serverClass:search_heads:app:flog_props_search]
restartSplunkd = false
stateOnClient = enabled

[serverClass:search_heads:app:1_all_forwarder_outputs]
restartSplunkd = true
stateOnClient = enabled
